package net.sergiobelli.jecon.be.orm;

// Generated 9-feb-2009 22.42.43 by Hibernate Tools 3.2.4.CR1

import java.util.Date;

/**
 * SdAccessi generated by hbm2java
 */
public class SdAccessi implements java.io.Serializable {

	private SdAccessiId id;
	private Date ora;

	public SdAccessi() {
	}

	public SdAccessi(SdAccessiId id, Date ora) {
		this.id = id;
		this.ora = ora;
	}

	public SdAccessiId getId() {
		return this.id;
	}

	public void setId(SdAccessiId id) {
		this.id = id;
	}

	public Date getOra() {
		return this.ora;
	}

	public void setOra(Date ora) {
		this.ora = ora;
	}

}
