package net.sergiobelli.jecon.be.orm;

// Generated 9-feb-2009 22.42.43 by Hibernate Tools 3.2.4.CR1

/**
 * SdTipiPagamentoId generated by hbm2java
 */
public class SdTipiPagamentoId implements java.io.Serializable {

	private int idTipoPagamento;
	private String tipoPagamento;

	public SdTipiPagamentoId() {
	}

	public SdTipiPagamentoId(int idTipoPagamento, String tipoPagamento) {
		this.idTipoPagamento = idTipoPagamento;
		this.tipoPagamento = tipoPagamento;
	}

	public int getIdTipoPagamento() {
		return this.idTipoPagamento;
	}

	public void setIdTipoPagamento(int idTipoPagamento) {
		this.idTipoPagamento = idTipoPagamento;
	}

	public String getTipoPagamento() {
		return this.tipoPagamento;
	}

	public void setTipoPagamento(String tipoPagamento) {
		this.tipoPagamento = tipoPagamento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SdTipiPagamentoId))
			return false;
		SdTipiPagamentoId castOther = (SdTipiPagamentoId) other;

		return (this.getIdTipoPagamento() == castOther.getIdTipoPagamento())
				&& ((this.getTipoPagamento() == castOther.getTipoPagamento()) || (this
						.getTipoPagamento() != null
						&& castOther.getTipoPagamento() != null && this
						.getTipoPagamento()
						.equals(castOther.getTipoPagamento())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTipoPagamento();
		result = 37
				* result
				+ (getTipoPagamento() == null ? 0 : this.getTipoPagamento()
						.hashCode());
		return result;
	}

}
