package net.sergiobelli.jecon.be.orm;

// Generated 9-feb-2009 22.42.43 by Hibernate Tools 3.2.4.CR1

/**
 * SdAnniBilancio generated by hbm2java
 */
public class SdAnniBilancio implements java.io.Serializable {

	private String anno;

	public SdAnniBilancio() {
	}

	public SdAnniBilancio(String anno) {
		this.anno = anno;
	}

	public String getAnno() {
		return this.anno;
	}

	public void setAnno(String anno) {
		this.anno = anno;
	}

}
