package net.sergiobelli.jecon.be.orm;

// Generated 9-feb-2009 22.42.43 by Hibernate Tools 3.2.4.CR1

/**
 * SdTipiPagamento generated by hbm2java
 */
public class SdTipiPagamento implements java.io.Serializable {

	private SdTipiPagamentoId id;

	public SdTipiPagamento() {
	}

	public SdTipiPagamento(SdTipiPagamentoId id) {
		this.id = id;
	}

	public SdTipiPagamentoId getId() {
		return this.id;
	}

	public void setId(SdTipiPagamentoId id) {
		this.id = id;
	}

}
