package net.sergiobelli.jecon.be.orm;

// Generated 9-feb-2009 22.42.43 by Hibernate Tools 3.2.4.CR1

/**
 * SdVociBilancioId generated by hbm2java
 */
public class SdVociBilancioId implements java.io.Serializable {

	private byte id;
	private String voce;

	public SdVociBilancioId() {
	}

	public SdVociBilancioId(byte id, String voce) {
		this.id = id;
		this.voce = voce;
	}

	public byte getId() {
		return this.id;
	}

	public void setId(byte id) {
		this.id = id;
	}

	public String getVoce() {
		return this.voce;
	}

	public void setVoce(String voce) {
		this.voce = voce;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SdVociBilancioId))
			return false;
		SdVociBilancioId castOther = (SdVociBilancioId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getVoce() == castOther.getVoce()) || (this.getVoce() != null
						&& castOther.getVoce() != null && this.getVoce()
						.equals(castOther.getVoce())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getVoce() == null ? 0 : this.getVoce().hashCode());
		return result;
	}

}
