package net.sergiobelli.jecon.be.orm;

// Generated 9-feb-2009 22.42.43 by Hibernate Tools 3.2.4.CR1

/**
 * SdBanche generated by hbm2java
 */
public class SdBanche implements java.io.Serializable {

	private Integer idBanca;
	private String banca;
	private String indirizzo;
	private String agenzia;
	private String abi;
	private String cab;
	private String conto;
	private String titolare;
	private char deleted;

	public SdBanche() {
	}

	public SdBanche(String banca, String indirizzo, String agenzia, String abi,
			String cab, String conto, String titolare, char deleted) {
		this.banca = banca;
		this.indirizzo = indirizzo;
		this.agenzia = agenzia;
		this.abi = abi;
		this.cab = cab;
		this.conto = conto;
		this.titolare = titolare;
		this.deleted = deleted;
	}

	public Integer getIdBanca() {
		return this.idBanca;
	}

	public void setIdBanca(Integer idBanca) {
		this.idBanca = idBanca;
	}

	public String getBanca() {
		return this.banca;
	}

	public void setBanca(String banca) {
		this.banca = banca;
	}

	public String getIndirizzo() {
		return this.indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	public String getAgenzia() {
		return this.agenzia;
	}

	public void setAgenzia(String agenzia) {
		this.agenzia = agenzia;
	}

	public String getAbi() {
		return this.abi;
	}

	public void setAbi(String abi) {
		this.abi = abi;
	}

	public String getCab() {
		return this.cab;
	}

	public void setCab(String cab) {
		this.cab = cab;
	}

	public String getConto() {
		return this.conto;
	}

	public void setConto(String conto) {
		this.conto = conto;
	}

	public String getTitolare() {
		return this.titolare;
	}

	public void setTitolare(String titolare) {
		this.titolare = titolare;
	}

	public char getDeleted() {
		return this.deleted;
	}

	public void setDeleted(char deleted) {
		this.deleted = deleted;
	}

}
