package net.sergiobelli.jecon.be.orm;

// Generated 9-feb-2009 22.42.43 by Hibernate Tools 3.2.4.CR1

/**
 * SdAdmin generated by hbm2java
 */
public class SdAdmin implements java.io.Serializable {

	private Integer idAdmin;
	private String cognome;
	private String nome;
	private int livello;
	private String login;
	private String password;
	private String email;

	public SdAdmin() {
	}

	public SdAdmin(String cognome, String nome, int livello, String login,
			String password) {
		this.cognome = cognome;
		this.nome = nome;
		this.livello = livello;
		this.login = login;
		this.password = password;
	}

	public SdAdmin(String cognome, String nome, int livello, String login,
			String password, String email) {
		this.cognome = cognome;
		this.nome = nome;
		this.livello = livello;
		this.login = login;
		this.password = password;
		this.email = email;
	}

	public Integer getIdAdmin() {
		return this.idAdmin;
	}

	public void setIdAdmin(Integer idAdmin) {
		this.idAdmin = idAdmin;
	}

	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public int getLivello() {
		return this.livello;
	}

	public void setLivello(int livello) {
		this.livello = livello;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
