package net.sergiobelli.jecon.be.orm;

// Generated 9-feb-2009 22.42.43 by Hibernate Tools 3.2.4.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SdMovimenti generated by hbm2java
 */
public class SdMovimenti implements java.io.Serializable {

	private Integer idMovimento;
	private String idSoggetto;
	private Date dataValuta;
	private String tipoPagamento;
	private BigDecimal entrate;
	private BigDecimal uscite;
	private String idBanca;
	private String descrizione;
	private byte idVoceBilancio;
	private Date dataCompetenza;
	private char deleted;
	private String idAdmin;
	private String annoBilancio;
	private Date dataInserimento;
	private Date dataModifica;
	private Date dataInserimento2;
	private Date dataInserimento3;
	private Date dataModifica2;
	private Date dataModifica3;

	public SdMovimenti() {
	}

	public SdMovimenti(String idSoggetto, Date dataValuta,
			String tipoPagamento, BigDecimal entrate, BigDecimal uscite,
			String idBanca, String descrizione, byte idVoceBilancio,
			Date dataCompetenza, char deleted, String idAdmin,
			String annoBilancio, Date dataInserimento, Date dataModifica,
			Date dataInserimento2, Date dataInserimento3, Date dataModifica2,
			Date dataModifica3) {
		this.idSoggetto = idSoggetto;
		this.dataValuta = dataValuta;
		this.tipoPagamento = tipoPagamento;
		this.entrate = entrate;
		this.uscite = uscite;
		this.idBanca = idBanca;
		this.descrizione = descrizione;
		this.idVoceBilancio = idVoceBilancio;
		this.dataCompetenza = dataCompetenza;
		this.deleted = deleted;
		this.idAdmin = idAdmin;
		this.annoBilancio = annoBilancio;
		this.dataInserimento = dataInserimento;
		this.dataModifica = dataModifica;
		this.dataInserimento2 = dataInserimento2;
		this.dataInserimento3 = dataInserimento3;
		this.dataModifica2 = dataModifica2;
		this.dataModifica3 = dataModifica3;
	}

	public Integer getIdMovimento() {
		return this.idMovimento;
	}

	public void setIdMovimento(Integer idMovimento) {
		this.idMovimento = idMovimento;
	}

	public String getIdSoggetto() {
		return this.idSoggetto;
	}

	public void setIdSoggetto(String idSoggetto) {
		this.idSoggetto = idSoggetto;
	}

	public Date getDataValuta() {
		return this.dataValuta;
	}

	public void setDataValuta(Date dataValuta) {
		this.dataValuta = dataValuta;
	}

	public String getTipoPagamento() {
		return this.tipoPagamento;
	}

	public void setTipoPagamento(String tipoPagamento) {
		this.tipoPagamento = tipoPagamento;
	}

	public BigDecimal getEntrate() {
		return this.entrate;
	}

	public void setEntrate(BigDecimal entrate) {
		this.entrate = entrate;
	}

	public BigDecimal getUscite() {
		return this.uscite;
	}

	public void setUscite(BigDecimal uscite) {
		this.uscite = uscite;
	}

	public String getIdBanca() {
		return this.idBanca;
	}

	public void setIdBanca(String idBanca) {
		this.idBanca = idBanca;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public byte getIdVoceBilancio() {
		return this.idVoceBilancio;
	}

	public void setIdVoceBilancio(byte idVoceBilancio) {
		this.idVoceBilancio = idVoceBilancio;
	}

	public Date getDataCompetenza() {
		return this.dataCompetenza;
	}

	public void setDataCompetenza(Date dataCompetenza) {
		this.dataCompetenza = dataCompetenza;
	}

	public char getDeleted() {
		return this.deleted;
	}

	public void setDeleted(char deleted) {
		this.deleted = deleted;
	}

	public String getIdAdmin() {
		return this.idAdmin;
	}

	public void setIdAdmin(String idAdmin) {
		this.idAdmin = idAdmin;
	}

	public String getAnnoBilancio() {
		return this.annoBilancio;
	}

	public void setAnnoBilancio(String annoBilancio) {
		this.annoBilancio = annoBilancio;
	}

	public Date getDataInserimento() {
		return this.dataInserimento;
	}

	public void setDataInserimento(Date dataInserimento) {
		this.dataInserimento = dataInserimento;
	}

	public Date getDataModifica() {
		return this.dataModifica;
	}

	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	public Date getDataInserimento2() {
		return this.dataInserimento2;
	}

	public void setDataInserimento2(Date dataInserimento2) {
		this.dataInserimento2 = dataInserimento2;
	}

	public Date getDataInserimento3() {
		return this.dataInserimento3;
	}

	public void setDataInserimento3(Date dataInserimento3) {
		this.dataInserimento3 = dataInserimento3;
	}

	public Date getDataModifica2() {
		return this.dataModifica2;
	}

	public void setDataModifica2(Date dataModifica2) {
		this.dataModifica2 = dataModifica2;
	}

	public Date getDataModifica3() {
		return this.dataModifica3;
	}

	public void setDataModifica3(Date dataModifica3) {
		this.dataModifica3 = dataModifica3;
	}

}
