package net.sergiobelli.jecon.be.orm;

// Generated 9-feb-2009 22.42.43 by Hibernate Tools 3.2.4.CR1

/**
 * SdVociBilancio generated by hbm2java
 */
public class SdVociBilancio implements java.io.Serializable {

	private SdVociBilancioId id;
	private char bilancio;

	public SdVociBilancio() {
	}

	public SdVociBilancio(SdVociBilancioId id, char bilancio) {
		this.id = id;
		this.bilancio = bilancio;
	}

	public SdVociBilancioId getId() {
		return this.id;
	}

	public void setId(SdVociBilancioId id) {
		this.id = id;
	}

	public char getBilancio() {
		return this.bilancio;
	}

	public void setBilancio(char bilancio) {
		this.bilancio = bilancio;
	}

}
